version: "3.8"

volumes:
  db-volume:

networks:
  express:

services:
  app_first:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=app:*
    ports:
      - 8080:3000
    tty: true
    volumes:
      - ./src:/app:cached
    networks:
      - express

  app_second:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=app:*
    tty: true
    ports:
      - 8888:3000
    volumes:
      - ./src2:/app:cached
    networks:
      - express

  ngrok:
    image: wernight/ngrok:latest
    ports:
      - 4041:4040
    environment:
      NGROK_PROTOCOL: http
      NGROK_PORT: app_second:3000
    depends_on:
      - app_second
    networks:
      - express
