version: "3.8"

volumes:
  db-volume:

networks:
  express:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=app:*
    ports:
      - 8080:3000
    tty: true
    volumes:
      - ./src:/app:cached
    networks:
      - express

  ngrok:
    image: wernight/ngrok:latest
    ports:
      - 4040:4040
    environment:
      NGROK_PROTOCOL: http
      NGROK_PORT: app:3000
    depends_on:
      - app
    networks:
      - express
